export const types={
    SET_PRODUCTS:'SET_PRODUCTS',
    SET_PRODUCT:'SET_PRODUCT',
    SET_CART_LIST:'SET_CART_LIST',
    DELETE_ITE_CART_LIST:'DELETE_ITE_CART_LIST',
    RESET_CART_LIST:'RESET_CART_LIST',
    SET_MENU_ITEMS:'SET_MENU_ITEMS'
}